/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomHeroImg: typeof import('./.vitepress/theme/components/CustomHeroImg.vue')['default']
    LayoutBottom: typeof import('./.vitepress/theme/components/LayoutBottom.vue')['default']
    MyToast: typeof import('./.vitepress/theme/components/MyToast.vue')['default']
    SpeechEasy: typeof import('./.vitepress/theme/components/SpeechEasy.vue')['default']
    TextInput: typeof import('./.vitepress/theme/components/TextInput.vue')['default']
    VPDocCustom: typeof import('./.vitepress/theme/components/VPDocCustom.vue')['default']
  }
}
