/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomLink: typeof import('./../.vitepress/theme/components/CustomLink.vue')['default']
    LayoutBottom: typeof import('./../.vitepress/theme/components/LayoutBottom.vue')['default']
    Read: typeof import('./../.vitepress/theme/components/Read.vue')['default']
  }
}
